version: '3.5'
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.selfhostedservices.acme.tlschallenge=true"
      - "--certificatesresolvers.selfhostedservices.acme.email=replace_with_working_email_address"
      - "--certificatesresolvers.selfhostedservices.acme.storage=/letsencrypt/acme.json"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  well-known:
    image: nginx:alpine
    container_name: well-known
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nostr.conf
      - ./nostr.json:/usr/share/nginx/html/.well-known/nostr.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.well-known.rule=Host(`replace_with_your_domain`) && PathPrefix(`/.well-known`)"
      - "traefik.http.services.well-known.loadbalancer.server.port=80"
      - "traefik.http.routers.well-known.entrypoints=websecure"
      - "traefik.http.routers.well-known.tls.certresolver=selfhostedservices"
      - "traefik.http.middlewares.accesscontrol.headers.customResponseHeaders.access-control-allow-origin=*"
      - "traefik.http.routers.well-known.middlewares=accesscontrol@docker"
